#!/bin/bash

if ! dpkg -s bluez > /dev/null 2>&1; then
    echo "Setting up bluetooth..."

    echo "Installing BlueZ..."
    apt-get update && apt-get install -y bluez git

    echo "Installing Raspberry Pi firmware tools..."
    git clone -b master --single-branch --depth 1 https://github.com/raspberrypi/firmware /tmp/firmware
    mv /tmp/firmware/hardfp/opt/vc /opt
    echo "/opt/vc/lib" > /etc/ld.so.conf.d/00-vmcs.conf
    ldconfig

    # (https://github.com/openhab/openhab-addons/issues/5680)
    echo "Downloading tinyb libraries..."
    JAVA_LIB_DIR="${JAVA_HOME}/jre/lib/aarch32"
    PERM_REF_FILE=$(ls $JAVA_LIB_DIR | head -n 1)
    curl -kL https://github.com/openhab/openhab-addons/raw/2.5.x/bundles/org.openhab.binding.bluetooth.bluez/src/main/resources/lib/armv6hf/libjavatinyb.so \
      -o "${JAVA_LIB_DIR}/libjavatinyb.so"
    curl -kL https://github.com/openhab/openhab-addons/raw/2.5.x/bundles/org.openhab.binding.bluetooth.bluez/src/main/resources/lib/armv6hf/libtinyb.so \
      -o "${JAVA_LIB_DIR}libtinyb.so"

    echo "Setting tinyb permissions using '${PERM_REF_FILE}' as reference..."
    chmod --reference "${JAVA_LIB_DIR}/${PERM_REF_FILE}" "${JAVA_LIB_DIR}/*"
    chown --reference "${JAVA_LIB_DIR}/${PERM_REF_FILE}" "${JAVA_LIB_DIR}/*"

    # give openHAB permission to use Bluetooth
    echo "Adding openHAB user to bluetooth group..."
    usermod -aG bluetooth openhab

    echo "Cleaning up..."
    apt-get purge --auto-remove -y git
    rm -rf /tmp/*
    rm -rf /opt/vc/src
    rm -rf /var/lib/apt/lists/*
else
    echo "Bluetooth is already setup!"
fi

