#!/bin/bash

# give OpenHAB permission to use Bluetooth
usermod -aG bluetooth openhab

# reset the Bluetooth chip
/opt/vc/bin/vcmailbox 0x38041 8 8 128 0
sleep 1

/opt/vc/bin/vcmailbox 0x38041 8 8 128 1
sleep 1

# initialize the Bluetooth chip
hciattach /dev/ttyAMA0 bcm43xx 921600

# start dbus and the Bluetooth daemon
/etc/init.d/dbus start
/etc/init.d/bluetooth start
